version: "3.1"
services:
  wallet:
    image: wallet
    build: ./
    ports:
      - "8082:8082"
    depends_on:
      - wallet_db
    container_name: wallet
  wallet_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wallet_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: --auth=md5
    container_name: wallet_db