env: "local" # local dev prod
storage_path: "postgresql://postgres:grosBerg22@:5432/wallet_db?sslmode=disable" # Будет порт для постгреса
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "admin"
  password: "admin"